### ISSUE TITLE
Make error: cannot convert ‘amqp_table_t’ to ‘amqp_boolean_t’ running on Centos

### ISSUE THREAD

**Issue by martinjkelly** [akalend/amqpcpp#38]
Hi,

I'm getting this error when trying to make amqpcpp on a 64 bit centos virtual machine.

make
g++  -Wall -I/usr/local/include -L/usr/local/lib -Iinclude/  -c -o src/AMQPExchange.o src/AMQPExchange.cpp
src/AMQPExchange.cpp: In member function ‘void AMQPExchange::sendDeclareCommand()’:
src/AMQPExchange.cpp:73: error: cannot convert ‘amqp_table_t’ to ‘amqp_boolean_t’ for argument ‘7’ to ‘amqp_exchange_declare_ok_t\* amqp_exchange_declare(amqp_connection_state_t__, amqp_channel_t, amqp_bytes_t, amqp_bytes_t, amqp_boolean_t, amqp_boolean_t, amqp_boolean_t, amqp_boolean_t, amqp_table_t)’
make: *_\* [src/AMQPExchange.o] Error 1

It works perfectly fine on my iMac.

I cannot seem to find the cause of the issue. any ideas?

**Comment by vltr** [comment]
@martinjkelly: bumped with the same issue. Newer versions of rabbitmq-c now breaks amqpcpp BUT I wouldn't consider a modification YET because amqpcpp is still compatible with the latest stable release of rabbitmq-c (0.5.2). The instructions of how to use amqpcpp by cloning rabbitmq-c repository directly is the faulty question here (at the time I'm writing). When 0.6 becomes stable, then amqpcpp would require code updates.

**Comment by vltr** [comment]
@martinjkelly: nevermind. The readme in rabbitmq-c is also wrong, saying the latest stable is indeed v0.6.0 but the link right bellow is to version 0.5.2. What a MESS ... :warning:

**Comment by martinjkelly** [comment]
see this SO post on how I worked around it at the time, I haven't looked at it since http://stackoverflow.com/questions/26703443/unable-to-compile-amqpcpp-make-error

**Comment by vltr** [comment]
Yup! I made the same change some hours ago to make it work with 0.6.x :) I
don't think the current author seems keen to continue this project. Maybe
someone could assume it under a new name and add all those changes (from
newer versions of rabbitmq-c to memory leak fixes). Anyone?
